# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xJnprX1h5tHl2rxXqtUGKdJRDPwmbe-v
"""

# --- Instalar bcrypt si no está presente ---
!pip install bcrypt --quiet

# --- Importar librerías ---
import bcrypt
import sqlite3
from datetime import datetime, timezone

# --- Configuración ---
DB_PATH = "users.db"
SEPARATOR = "_"
STORE_CLEARTEXT_FOR_CLASS = False  # Cambia a True solo para guardar contraseñas en texto plano

# --- Datos: 23 filas del formulario ---
rows = [
    ("user1", "Mi pez favorito, mi clado taxonomico favorito, un organulo de la celula vegetal"),
    ("user2", "cafe, libro, flor"),
    ("user3", "Apellido, DNI, numero de teléfono"),
    ("user4", "Pacopiso Marzo Cachivache"),
    ("user5", "Nala, Baskonia, Ribabellosa"),
    ("user6", "Barandiaran, Badaia, Alan"),
    ("user7", "Rueda, luz, puerta"),
    ("user8", "Julio, cerveza, fútbol."),
    ("user9", "Croqueta, fentanilo, Mariano"),
    ("user10", "Nombre de mi mascota, nombre de mi equipo de fútbol favorito, nombre de mi jugador favorito"),
    ("user11", "Baskonia, Mus, Gasteiz"),
    ("user12", "Robert, 26/04/2025, Porsche"),
    ("user13", "vitoria, 23, bocajr"),
    ("user14", "Animal,Año,NombreFamiliar"),
    ("user15", "Arrigo Opel Athletic"),
    ("user16", "Mus,Luis,Alaves"),
    ("user17", "cazador, Cuautepec, Bustamante."),
    ("user18", "Duke, Tías, Portátil"),
    ("user19", "Ordenador, letras, mascota"),
    ("user20", "Chivas, paraiso, acámbaro"),
    ("user21", "menditxo,unamuno,blackjack"),
    ("user22", "balón, poker, dinero"),
    ("user23", "Emi, rocallosas, 27/04/04"),
]

# --- Funciones auxiliares ---

def split_into_three(raw_line):
    """Divide la cadena original en 3 partes, priorizando comas"""
    parts = [p.strip().strip(".") for p in raw_line.split(",")]
    parts = [p for p in parts if p != ""]
    if len(parts) == 3:
        return parts
    # fallback: dividir por palabras
    words = raw_line.replace(".", "").split()
    if len(words) >= 3:
        n = len(words)
        a = " ".join(words[: max(1, n//3)])
        b = " ".join(words[max(1, n//3): 2*max(1, n//3)])
        c = " ".join(words[2*max(1, n//3):])
        return [a.strip(), b.strip(), c.strip()]
    return [raw_line, "", ""]

def make_password(parts, sep=SEPARATOR):
    """Une las 3 partes en una contraseña simple"""
    parts_clean = [p.replace(" ", "") for p in parts]
    return sep.join(parts_clean)

def hash_password_bcrypt(password):
    """Genera hash seguro con bcrypt (trunca a 72 bytes si es necesario)"""
    pw_bytes = password.encode("utf-8")
    if len(pw_bytes) > 72:
        print(f"[WARN] Contraseña de {len(pw_bytes)} bytes truncada a 72 bytes.")
        pw_bytes = pw_bytes[:72]
    salt = bcrypt.gensalt(rounds=12)
    hashed = bcrypt.hashpw(pw_bytes, salt)
    return hashed.decode("utf-8")

def verify_password_bcrypt(password, hashed):
    """Verifica si una contraseña coincide con su hash"""
    pw_bytes = password.encode("utf-8")[:72]
    return bcrypt.checkpw(pw_bytes, hashed.encode("utf-8"))

# --- Base de datos ---

def init_db(conn):
    """Crea la tabla users si no existe"""
    cur = conn.cursor()
    cur.execute("""
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT UNIQUE NOT NULL,
            password_hash TEXT NOT NULL,
            created_at TEXT NOT NULL,
            cleartext_demo TEXT
        );
    """)
    conn.commit()

def insert_user(conn, username, password_hash, cleartext=None):
    """Inserta un usuario con su hash en la base de datos"""
    cur = conn.cursor()
    cur.execute("""
        INSERT OR REPLACE INTO users (username, password_hash, created_at, cleartext_demo)
        VALUES (?, ?, ?, ?)
    """, (username, password_hash, datetime.now(timezone.utc).isoformat(), cleartext))
    conn.commit()

# --- Proceso principal ---

def main():
    print("\nCreando base de datos SQLite → users.db\n")
    conn = sqlite3.connect(DB_PATH)
    init_db(conn)

    for uid, raw in rows:
        parts = split_into_three(raw)
        password = make_password(parts)
        hashed = hash_password_bcrypt(password)
        cleartext_store = password if STORE_CLEARTEXT_FOR_CLASS else None
        insert_user(conn, uid, hashed, cleartext_store)
        print(f"[OK] {uid}: '{password}'  → HASH guardado")

    # Verificación de ejemplo
    print("\n--- Verificación de prueba con user1 ---")
    cur = conn.cursor()
    cur.execute("SELECT password_hash FROM users WHERE username='user1'")
    row = cur.fetchone()
    if row:
        h = row[0]
        pw_local = make_password(split_into_three(rows[0][1]))
        ok = verify_password_bcrypt(pw_local, h)
        print("Verificación user1:", ok)

    conn.close()
    print("\nFinalizado. Archivo generado: users.db ✅")

# Ejecutar
if __name__ == "__main__":
    main()