# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uREcSnZYByEwVWnz9T9B-RdKt5thAIiw
"""

# --- Instalar dependencias ---
!pip install bcrypt --quiet
!pip install argon2-cffi --quiet
!pip install mysql-connector-python --quiet

# --- Importar librerías ---
import bcrypt
import sqlite3
from datetime import datetime, timezone
from argon2 import PasswordHasher
import mysql.connector
from google.colab import files

# --- Configuración ---
DB_PATH = "users.db"
SEPARATOR = "_"
STORE_CLEARTEXT_FOR_CLASS = True  # Guardar contraseñas en texto plano para migración

MYSQL_HOST = "localhost"       # Cambiar por tu host MySQL
MYSQL_USER = "TU_USUARIO"      # Cambiar por tu usuario MySQL
MYSQL_PASSWORD = "TU_CONTRASEÑA"  # Cambiar por tu contraseña MySQL
MYSQL_DB = "TU_BASE_DE_DATOS"  # Cambiar por tu base de datos MySQL

# --- Datos: 23 filas del formulario ---
rows = [
    ("user1", "Mi pez favorito, mi clado taxonomico favorito, un organulo de la celula vegetal"),
    ("user2", "cafe, libro, flor"),
    ("user3", "Apellido, DNI, numero de teléfono"),
    ("user4", "Pacopiso Marzo Cachivache"),
    ("user5", "Nala, Baskonia, Ribabellosa"),
    ("user6", "Barandiaran, Badaia, Alan"),
    ("user7", "Rueda, luz, puerta"),
    ("user8", "Julio, cerveza, fútbol."),
    ("user9", "Croqueta, fentanilo, Mariano"),
    ("user10", "Nombre de mi mascota, nombre de mi equipo de fútbol favorito, nombre de mi jugador favorito"),
    ("user11", "Baskonia, Mus, Gasteiz"),
    ("user12", "Robert, 26/04/2025, Porsche"),
    ("user13", "vitoria, 23, bocajr"),
    ("user14", "Animal,Año,NombreFamiliar"),
    ("user15", "Arrigo Opel Athletic"),
    ("user16", "Mus,Luis,Alaves"),
    ("user17", "cazador, Cuautepec, Bustamante."),
    ("user18", "Duke, Tías, Portátil"),
    ("user19", "Ordenador, letras, mascota"),
    ("user20", "Chivas, paraiso, acámbaro"),
    ("user21", "menditxo,unamuno,blackjack"),
    ("user22", "balón, poker, dinero"),
    ("user23", "Emi, rocallosas, 27/04/04"),
]

# --- Funciones auxiliares ---
def split_into_three(raw_line):
    parts = [p.strip().strip(".") for p in raw_line.split(",")]
    parts = [p for p in parts if p != ""]
    if len(parts) == 3:
        return parts
    words = raw_line.replace(".", "").split()
    if len(words) >= 3:
        n = len(words)
        a = " ".join(words[: max(1, n//3)])
        b = " ".join(words[max(1, n//3): 2*max(1, n//3)])
        c = " ".join(words[2*max(1, n//3):])
        return [a.strip(), b.strip(), c.strip()]
    return [raw_line, "", ""]

def make_password(parts, sep=SEPARATOR):
    parts_clean = [p.replace(" ", "") for p in parts]
    return sep.join(parts_clean)

def hash_password_bcrypt(password):
    pw_bytes = password.encode("utf-8")
    if len(pw_bytes) > 72:
        pw_bytes = pw_bytes[:72]
    salt = bcrypt.gensalt(rounds=12)
    hashed = bcrypt.hashpw(pw_bytes, salt)
    return hashed.decode("utf-8")

def insert_user_sqlite(conn, username, password_hash, cleartext=None):
    cur = conn.cursor()
    cur.execute("""
        INSERT OR REPLACE INTO users (username, password_hash, created_at, cleartext_demo)
        VALUES (?, ?, ?, ?)
    """, (username, password_hash, datetime.now(timezone.utc).isoformat(), cleartext))
    conn.commit()

def init_db(conn):
    cur = conn.cursor()
    cur.execute("""
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            username TEXT UNIQUE NOT NULL,
            password_hash TEXT NOT NULL,
            created_at TEXT NOT NULL,
            cleartext_demo TEXT
        );
    """)
    conn.commit()

# --- Crear SQLite DB ---
conn_sqlite = sqlite3.connect(DB_PATH)
init_db(conn_sqlite)

for uid, raw in rows:
    parts = split_into_three(raw)
    password = make_password(parts)
    hashed = hash_password_bcrypt(password)
    cleartext_store = password if STORE_CLEARTEXT_FOR_CLASS else None
    insert_user_sqlite(conn_sqlite, uid, hashed, cleartext_store)

conn_sqlite.close()
print("SQLite DB creada ✅")

# --- Descargar SQLite DB ---
files.download(DB_PATH)

# --- Migrar a MySQL con Argon2 ---
try:
    conn_mysql = mysql.connector.connect(
        host=MYSQL_HOST,
        user=MYSQL_USER,
        password=MYSQL_PASSWORD,
        database=MYSQL_DB
    )
    cur_mysql = conn_mysql.cursor()

    # Crear tabla equivalente
    cur_mysql.execute("""
    CREATE TABLE IF NOT EXISTS users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        username VARCHAR(255) UNIQUE NOT NULL,
        password_hash TEXT NOT NULL,
        created_at DATETIME NOT NULL
    )
    """)

    # Leer SQLite y generar Argon2
    ph = PasswordHasher()
    conn_sqlite = sqlite3.connect(DB_PATH)
    cur_sqlite = conn_sqlite.cursor()
    cur_sqlite.execute("SELECT username, cleartext_demo FROM users")
    users_data = cur_sqlite.fetchall()
    conn_sqlite.close()

    for username, cleartext in users_data:
        if cleartext is None:
            continue
        hash_argon2 = ph.hash(cleartext)
        cur_mysql.execute(
            "INSERT INTO users (username, password_hash, created_at) VALUES (%s, %s, %s)",
            (username, hash_argon2, datetime.utcnow())
        )

    conn_mysql.commit()
    conn_mysql.close()
    print("Migración a MySQL completada ✅")

except Exception as e:
    print("Error al conectar a MySQL:", e)
import sqlite3

DB_PATH = "users.db"

conn = sqlite3.connect(DB_PATH)
cur = conn.cursor()

# Ver todas las tablas
cur.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cur.fetchall()
print("Tablas en la base de datos:", tables)

# Ver cuántas filas hay en 'users'
cur.execute("SELECT COUNT(*) FROM users;")
count = cur.fetchone()[0]
print("Número de usuarios:", count)

# Ver los primeros 5 registros
cur.execute("SELECT * FROM users LIMIT 5;")
rows = cur.fetchall()
for row in rows:
    print(row)

conn.close()